### ISSUE TITLE
小米8无法安装提供的apk

### ISSUE THREAD

**Issue by GuangYiL** [zhiwei1990/android-jetpack-demo#1]

**Comment by zhiwei1990** [comment]
感谢你的提议，最近忙于公司项目架构，更新较少。按说原码编译的apk应该可以运行，二维码里面的是1.0的，比较早。近期也在梳理kotlin，jetpack在公司项目使用中的一些问题与注意点，会适时的更新该项目，再次感谢你的支持！

**Comment by zhiwei1990** [comment]
> _No description provided._

感谢你的提议，最近忙于公司项目架构，更新较少。按说原码编译的apk应该可以运行，二维码里面的是1.0的，比较早。近期也在梳理kotlin，jetpack在公司项目使用中的一些问题与注意点，会适时的更新该项目，再次感谢你的支持！
