### ISSUE TITLE
结果有误

### ISSUE THREAD

**Issue by LomoLin** [zhiwei1990/android-jetpack-demo#2]
从实验结果来看，fuser点击button是会响应name的改变的，不管是从您提供的apk还是我自己动手敲的代码，结果都一样，与您说的结果不一致

R.id.btn_change_field -> {
				fuser.name = "李四/里斯"
				fuser.age.set(20);fuser.desc.set("这两个field可以改变，你会发现名字name是不改变的")
			}，结果名字还是会改变成"李四/李斯"。

**Comment by LomoLin** [comment]
能否说明下结果不一致的原因呢？

**Comment by zhiwei1990** [comment]
首先谢谢你的反馈。我也做了认真的分析，并做了对比和验证。

确实如你所说，现在在FieldUser中只要有一个Observable的属性修改，再修改其他即使不是Observable的值后，UI也会被刷新。

*鉴于代码也是我当时学习的笔记，中间经过一次Java版改Kotlin的修改，可能引起错误。*

我方才也用Java代码做了验证。问题如你所述。经分析代码和查看binding源码，得到结果就是

**FieldUser中只要有一个Observable的属性，在修改变量后，整个User对象都会被刷新。**

user的binding流程：第一次setUser时候，在对应xml的BindingImpl中调用`invalidateAll()`->`requestReBind()`，而后`executeBindings()`
之后的changeField的时候，回调用`onFiledChange`->`onChangeXXX`,里面都会修改`mDirtyFlags`这个标记，并且在`executeBindings()`中，根据这个标记更新所有User的属性值。


> PS：或许是以前版本databinding能做到局部刷新，也可能是一开始我的描述就出了错误。不再纠结。目前AS版本结论如上。

**Comment by zhiwei1990** [comment]
> 能否说明下结果不一致的原因呢？

首先谢谢你的反馈。我也做了认真的分析，并做了对比和验证。

确实如你所说，现在在FieldUser中只要有一个Observable的属性修改，再修改其他即使不是Observable的值后，UI也会被刷新。

鉴于代码也是我当时学习的笔记，中间经过一次Java版改Kotlin的修改，可能引起错误。

我方才也用Java代码做了验证。问题如你所述。经分析代码和查看binding源码，得到结果就是

FieldUser中只要有一个Observable的属性，在修改变量后，整个User对象都会被刷新。

user的binding流程：第一次setUser时候，在对应xml的BindingImpl中调用invalidateAll()->requestReBind()，而后executeBindings()
之后的changeField的时候，回调用onFiledChange->onChangeXXX,里面都会修改mDirtyFlags这个标记，并且在executeBindings()中，根据这个标记更新所有User的属性值。

PS：或许是以前版本databinding能做到局部刷新，也可能是一开始我的描述就出了错误。不再纠结。目前AS版本结论如上。

**Comment by LomoLin** [comment]
> > 能否说明下结果不一致的原因呢？
> 
> 首先谢谢你的反馈。我也做了认真的分析，并做了对比和验证。
> 
> 确实如你所说，现在在FieldUser中只要有一个Observable的属性修改，再修改其他即使不是Observable的值后，UI也会被刷新。
> 
> _鉴于代码也是我当时学习的笔记，中间经过一次Java版改Kotlin的修改，可能引起错误。_
> 
> 我方才也用Java代码做了验证。问题如你所述。经分析代码和查看binding源码，得到结果就是
> 
> **FieldUser中只要有一个Observable的属性，在修改变量后，整个User对象都会被刷新。**
> 
> ```kotlin
> user的binding流程：第一次setUser时候，在对应xml的BindingImpl中调用invalidateAll()->requestReBind()，而后executeBindings()
> 之后的changeField的时候，回调用onFiledChange->onChangeXXX,里面都会修改mDirtyFlags这个标记，并且在executeBindings()中，根据这个标记更新所有User的属性值。
> ```
> 
> > PS：或许是以前版本databinding能做到局部刷新，也可能是一开始我的描述就出了错误。不再纠结。目前AS版本结论如上。

使用@Bindable也是如此。
感谢你的回答解惑。
